/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Taxibolaget;

import java.awt.Color;

/**
 *
 * @author Micke
 */
public class Numbers extends javax.swing.JFrame {

    /**
     * Creates new form Numbers
     */
    public Numbers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jScrollPane1.setEnabled(false);
        jScrollPane1.setFocusable(false);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Taxi Bolaget!");
        setBackground(new java.awt.Color(204, 0, 102));

        jPanel3.setBackground(new java.awt.Color(0, 155, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Car 3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel3.setToolTipText("Bil 3");
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setName(""); // NOI18N

        jButton5.setBackground(new java.awt.Color(0, 155, 0));
        jButton5.setText("Boka!");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 155, 0));
        jButton6.setText("Avboka");
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Raul Andersson - 5 år", "Anna Åbäck - 10 år", "Gustaf Nyström - 1 år", "Anders Loven - 2 år", "Annie Löfdahl - 3 år", "Levvy Machiabri - 5 år", "Jalmar Lövgren - 25 år" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tillgänglig");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(35, 35, 35))
        );

        jPanel4.setBackground(new java.awt.Color(0, 155, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Car 4", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jButton7.setBackground(new java.awt.Color(0, 155, 0));
        jButton7.setText("Boka!");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(0, 155, 0));
        jButton8.setText("Avboka");
        jButton8.setEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Raul Andersson - 5 år", "Anna Åbäck - 10 år", "Gustaf Nyström - 1 år", "Anders Loven - 2 år", "Annie Löfdahl - 3 år", "Levvy Machiabri - 5 år", "Jalmar Lövgren - 25 år" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tillgänglig");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(24, 24, 24))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(30, 30, 30))
        );

        jPanel5.setBackground(new java.awt.Color(0, 155, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Car 5", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jButton9.setBackground(new java.awt.Color(0, 155, 0));
        jButton9.setText("Boka!");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(0, 155, 0));
        jButton10.setText("Avboka");
        jButton10.setEnabled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Raul Andersson - 5 år", "Anna Åbäck - 10 år", "Gustaf Nyström - 1 år", "Anders Loven - 2 år", "Annie Löfdahl - 3 år", "Levvy Machiabri - 5 år", "Jalmar Lövgren - 25 år" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tillgänglig");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton9)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel5)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addGap(35, 35, 35))
        );

        jPanel1.setBackground(new java.awt.Color(0, 155, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Car 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setToolTipText("Car 1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Raul Andersson - 5 år", "Anna Åbäck - 10 år", "Gustaf Nyström - 1 år", "Anders Loven - 2 år", "Annie Löfdahl - 3 år", "Levvy Machiabri - 5 år", "Jalmar Lövgren - 25 år" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 155, 0));
        jButton1.setText("Boka!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 155, 0));
        jButton2.setText("Avboka");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Tillgänglig");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(39, 39, 39))
        );

        jPanel2.setBackground(new java.awt.Color(0, 155, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Car 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.setToolTipText("Car 2");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Raul Andersson - 5 år", "Anna Åbäck - 10 år", "Gustaf Nyström - 1 år", "Anders Loven - 2 år", "Annie Löfdahl - 3 år", "Levvy Machiabri - 5 år", "Jalmar Lövgren - 25 år" }));

        jButton3.setBackground(new java.awt.Color(0, 155, 0));
        jButton3.setText("Boka!");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 155, 0));
        jButton4.setText("Avboka");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tillgänglig");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void take_away(Object something, int boxing, int index){
        //take_away, handles removing of values from other comboBoxes, that should not contain
        //the name of a driver, if it's booked in one list - And replaces it with "Ingen Förare".
        
        //Based on the input of boxing, in the Switch, we know what "box" (ComboBox) we are handling -
        //thus, we can appropiately remove and add, to respective lists.
        
        
        switch(boxing){
            case 1:
                
                jComboBox2.removeItem(something);   
                jComboBox2.insertItemAt("Ingen Förare", index);
            
                
                jComboBox3.removeItem(something); 
                jComboBox3.insertItemAt("Ingen Förare", index);
               
                
                jComboBox4.removeItem(something);  
                jComboBox4.insertItemAt("Ingen Förare", index);
              
                
                jComboBox5.removeItem(something);   
                jComboBox5.insertItemAt("Ingen Förare", index);                
                break;
            case 2:
                jComboBox1.removeItem(something);   
                jComboBox1.insertItemAt("Ingen Förare", index);
                
                
                jComboBox3.removeItem(something);   
                jComboBox3.insertItemAt("Ingen Förare", index);
               
                
                jComboBox4.removeItem(something); 
                jComboBox4.insertItemAt("Ingen Förare", index);
                
                
                jComboBox5.removeItem(something);
                jComboBox5.insertItemAt("Ingen Förare", index);                
                break;
                  
            case 3:
                jComboBox1.removeItem(something);
                jComboBox1.insertItemAt("Ingen Förare", index);
                
                
                jComboBox2.removeItem(something);
                jComboBox2.insertItemAt("Ingen Förare", index);
                
                
                jComboBox4.removeItem(something);
                jComboBox4.insertItemAt("Ingen Förare", index);
                
                
                jComboBox5.removeItem(something);
                jComboBox5.insertItemAt("Ingen Förare", index);
                break;
                  
            case 4:
                jComboBox1.removeItem(something);
                jComboBox1.insertItemAt("Ingen Förare", index);
                
                
                jComboBox2.removeItem(something);
                jComboBox2.insertItemAt("Ingen Förare", index);
                
                
                jComboBox3.removeItem(something);
                jComboBox3.insertItemAt("Ingen Förare", index);
                
                
                jComboBox5.removeItem(something);
                jComboBox5.insertItemAt("Ingen Förare", index);
                break;
            case 5:
                jComboBox1.removeItem(something);
                jComboBox1.insertItemAt("Ingen Förare", index);
                
                
                jComboBox2.removeItem(something);
                jComboBox2.insertItemAt("Ingen Förare", index);
                
                
                jComboBox3.removeItem(something);
                jComboBox3.insertItemAt("Ingen Förare", index);
                
                
                jComboBox4.removeItem(something);
                jComboBox4.insertItemAt("Ingen Förare", index);                
                break;
        }    
    }
    private void box(Object input, int boxing, int index){
        //Box is much akin to take_away, except we use it to put values back in
        //and remove overflowing "Ingen Förare" values, to show that Drivers have returned/are available.
        switch (boxing) {
            case 1:
                jComboBox2.insertItemAt((String)input, index);
                jComboBox2.removeItemAt(index+1);
                
                
                jComboBox3.insertItemAt((String)input, index);
                jComboBox3.removeItemAt(index+1);
                
                jComboBox4.insertItemAt((String)input, index);
                jComboBox4.removeItemAt(index+1);
                
                jComboBox5.insertItemAt((String)input, index);
                jComboBox5.removeItemAt(index+1);
                break;
            case 2:
                jComboBox1.insertItemAt((String)input, index);
                jComboBox1.removeItemAt(index+1);
                
                jComboBox3.insertItemAt((String)input, index);
                jComboBox3.removeItemAt(index+1);
                
                jComboBox4.insertItemAt((String)input, index);
                jComboBox4.removeItemAt(index+1);
                
                jComboBox5.insertItemAt((String)input, index);
                jComboBox5.removeItemAt(index+1);
                break;
            case 3:
                jComboBox1.insertItemAt((String)input, index);
                jComboBox1.removeItemAt(index+1);
                
                jComboBox2.insertItemAt((String)input, index);
                jComboBox2.removeItemAt(index+1);
                
                jComboBox4.insertItemAt((String)input, index);
                jComboBox4.removeItemAt(index+1);
                
                jComboBox5.insertItemAt((String)input, index);
                jComboBox5.removeItemAt(index+1);               
                break;
            case 4:
                jComboBox1.insertItemAt((String)input, index);
                jComboBox1.removeItemAt(index+1);
                
                jComboBox2.insertItemAt((String)input, index);
                jComboBox2.removeItemAt(index+1);
                
                jComboBox3.insertItemAt((String)input, index);
                jComboBox3.removeItemAt(index+1);
                
                jComboBox5.insertItemAt((String)input, index);
                jComboBox5.removeItemAt(index+1);               
                break;
            case 5:
                jComboBox1.insertItemAt((String)input, index);
                jComboBox1.removeItemAt(index+1);
                
                jComboBox2.insertItemAt((String)input, index);
                jComboBox2.removeItemAt(index+1);
                
                jComboBox3.insertItemAt((String)input, index);
                jComboBox3.removeItemAt(index+1);
                
                jComboBox4.insertItemAt((String)input, index);
                jComboBox4.removeItemAt(index+1);               
                break;            
        }
    }
    
    private void box_check(String input, int box){
        //box_check handles Enabling of Buttons and Formatting of Colors/backgrounds.
        if(input.equals("Bokning")){ //In case of handling a Booking input
            Color red = new Color(155,0,0);
            switch(box){
                case 1:
                    jLabel1.setText("Bokad");
                    jPanel1.setBackground(red);
                    
                    jButton1.setEnabled(false);
                    
                    jButton2.setEnabled(true);
                    jButton2.setBackground(red);
                    
                    jComboBox1.setEnabled(false);
                    break;
                case 2:
                    jLabel2.setText("Bokad");
                    jPanel2.setBackground(red);
                    
                    jButton3.setEnabled(false);
                    
                    jButton4.setEnabled(true);
                    jButton4.setBackground(red);
                    
                    jComboBox2.setEnabled(false);
                    break;
                case 3:
                    jLabel3.setText("Bokad");
                    jPanel3.setBackground(red);
                    
                    jButton5.setEnabled(false);
                    
                    jButton6.setEnabled(true);
                    jButton6.setBackground(red);
                    
                    jComboBox3.setEnabled(false);
                    break;
                case 4:
                    jLabel4.setText("Bokad");
                    jPanel4.setBackground(red);
                    
                    jButton7.setEnabled(false);
                    
                    jButton8.setEnabled(true);
                    jButton8.setBackground(red);
                    
                    jComboBox4.setEnabled(false);
                    break;
                case 5:
                    jLabel5.setText("Bokad");                    
                    jPanel5.setBackground(red);
                    
                    jButton9.setEnabled(false);
                    
                    jButton10.setEnabled(true);
                    jButton10.setBackground(red);
                    
                    jComboBox5.setEnabled(false);
                    break;
                    
            }
        }
        else{ //In case of handling a Freeing up of time, input
            Color green = new Color(0, 155,0);
            switch(box){
                case 1:
                    jLabel1.setText("Tillgänglig");                   
                    jPanel1.setBackground(green);
                    
                    jButton1.setEnabled(true);
                    
                    jButton2.setEnabled(false);
                    
                    jComboBox1.setEnabled(true);
                    break;
                case 2:
                    jLabel2.setText("Tillgänglig");
                    jPanel2.setBackground(green);
                    
                    jButton3.setEnabled(true);
                    
                    jButton4.setEnabled(false);
                    
                    jComboBox2.setEnabled(true);
                    break;
                case 3:
                    jLabel3.setText("Tillgänglig");
                    jPanel3.setBackground(green);
                    
                    jButton5.setEnabled(true);
                    
                    jButton6.setEnabled(false);
                    
                    jComboBox3.setEnabled(true);
                    break;
                case 4:
                    jLabel4.setText("Tillgänglig");
                    jPanel4.setBackground(green);
                    
                    jButton7.setEnabled(true);
                    
                    jButton8.setEnabled(false);
                    
                    jComboBox4.setEnabled(true);
                    break;
                case 5:
                    jLabel5.setText("Tillgänglig");
                    jPanel5.setBackground(green);
                    
                    jButton9.setEnabled(true);
                    
                    jButton10.setEnabled(false);
                    
                    jComboBox5.setEnabled(true);
                    break;
                    
            }
        }
    }
    private void put_back(Object input, int box){
        //We accept the input String as a object, and check to see if it's containing value is of
        //a certain one.
        
        //Each value has a assigned spot, so that the list always ends up the same/fills out known spots
        //as to keep structure.

        if(input.equals("Raul Andersson - 5 år")){
            //Box is the method that handles the actual putting back of values and indexes of their respective spots etc.
                box(input, box, 0);          
        }
        else if(input.equals("Anna Åbäck - 10 år")){
            box(input, box, 1);
        }
        else if(input.equals("Gustaf Nyström - 1 år")){
            box(input, box, 2);
        }
        else if(input.equals("Anders Loven - 2 år")){
            box(input, box, 3);
        }
        else if(input.equals("Annie Löfdahl - 3 år")){
            box(input, box, 4);
        }
        else if(input.equals("Levvy Machiabri - 5 år")){
            box(input, box, 5);
        }
        else if(input.equals("Jalmar Lövgren - 25 år")){
            box(input, box, 6);
        }
       
    }    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
        
 
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Avbokning av Car 1
        
        //Since the format of Every Action method is the same, except for withdraw/put_back
        //Then i will put Commenting for Action buttions, in this Method, and the Next One.
        
        //Every time we try to click to Reserve/Free a time, we do a Check if a Driver is selected.
        if(!(jComboBox1.getSelectedItem().equals("Ingen Förare"))){
            box_check("Avbokning", 1);
            //the box_check method is responsible for formatting of Color, enabling/disabling buttons
            
            Object something = jComboBox1.getSelectedItem();
            //This is the Object that feed into the put_back method, where we put the values
            //back on their Indexes
            
            
            put_back(something, 1); 
            //Put_back is a "Checking" method, that checks the input based on the String value and the Box
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //Bokning av Car 1
        
 
        
      
        if(!(jComboBox1.getSelectedItem().equals("Ingen Förare"))){ 
          box_check("Bokning", 1);
        

          Object something = jComboBox1.getSelectedItem();
          
          int index = jComboBox1.getSelectedIndex();
          take_away(something, 1, index);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Bokning av Car 2
        
     
        if(!(jComboBox2.getSelectedItem().equals("Ingen Förare"))){ 
          box_check("Bokning", 2); 
        

          Object something = jComboBox2.getSelectedItem();
          
          
          int index = jComboBox2.getSelectedIndex();
          //To properly assert the Position of the Value into the ComboBox, we have to get the Index
          
          take_away(something, 2, index);
          //Take away is responsible for when we Remove the drivers name from all the other lists
          //and replace it with "Ingen Förare";
          //Which acts both as a Non-interactive Button (does nothing)
          //and
          //Acts as a "Buffer", to prevent OutOfReachExceptions in Array Handling of the Indexes
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Avbokning av Car 2
        
   
        if(!(jComboBox2.getSelectedItem().equals("Ingen Förare"))){
            box_check("Avbokning", 2);
          
          
            Object something = jComboBox2.getSelectedItem();
           
            
            put_back(something, 2);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Bokning av Car 3
        
    
        if(!(jComboBox3.getSelectedItem().equals("Ingen Förare"))){ 
          box_check("Bokning", 3);

          Object something = jComboBox3.getSelectedItem();
          int index = jComboBox3.getSelectedIndex();
          take_away(something, 3, index);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //Avbokning av Car 3
        
   
        if(!(jComboBox3.getSelectedItem().equals("Ingen Förare"))){ 
          box_check("Avbokning", 3);

          Object something = jComboBox3.getSelectedItem();
          put_back(something, 3);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //Bokning av Car 4
        

        if(!(jComboBox4.getSelectedItem().equals("Ingen Förare"))){ 
          box_check("Bokning", 4);

          Object something = jComboBox4.getSelectedItem();
          int index = jComboBox4.getSelectedIndex();
          take_away(something, 4, index);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //Avbokning av Car 4
        

        if(!(jComboBox4.getSelectedItem().equals("Ingen Förare"))){ 
          box_check("Avbokning", 4);

          Object something = jComboBox4.getSelectedItem();
          put_back(something, 4);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //Bokning av Car 5
        
  
        if(!(jComboBox5.getSelectedItem().equals("Ingen Förare"))){ 
          box_check("Bokning", 5);

          Object something = jComboBox5.getSelectedItem();
          int index = jComboBox5.getSelectedIndex();
          take_away(something, 5, index);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        //Avbokning av Car 5
        
 
        if(!(jComboBox5.getSelectedItem().equals("Ingen Förare"))){ 
          box_check("Avbokning", 5);

          Object something = jComboBox5.getSelectedItem();
          put_back(something, 5);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Numbers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Numbers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Numbers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Numbers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Numbers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
